// Date: 18/10/2014 22:00:53
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.MysticalWonders.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMysticalChair extends ModelBase
{
  //fields
    ModelRenderer leg_1;
    ModelRenderer leg_2;
    ModelRenderer leg_3;
    ModelRenderer leg_4;
    ModelRenderer Chair_top;
    ModelRenderer Chari_rod_1;
    ModelRenderer Chari_rod_2;
    ModelRenderer Chari_rod_3;
    ModelRenderer Chair_rod_4;
  
  public ModelMysticalChair()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      leg_1 = new ModelRenderer(this, 25, 13);
      leg_1.addBox(5F, 14F, 5F, 2, 10, 2);
      leg_1.setRotationPoint(0F, 0F, 0F);
      leg_1.setTextureSize(64, 32);
      leg_1.mirror = true;
      setRotation(leg_1, 0F, 0F, 0F);
      leg_2 = new ModelRenderer(this, 12, 13);
      leg_2.addBox(0F, 0F, 0F, 2, 10, 2);
      leg_2.setRotationPoint(5F, 14F, -7F);
      leg_2.setTextureSize(64, 32);
      leg_2.mirror = true;
      setRotation(leg_2, 0F, 0F, 0F);
      leg_3 = new ModelRenderer(this, 2, 13);
      leg_3.addBox(0F, 0F, 0F, 2, 10, 2);
      leg_3.setRotationPoint(-7F, 14F, 5F);
      leg_3.setTextureSize(64, 32);
      leg_3.mirror = true;
      setRotation(leg_3, 0F, 0F, 0F);
      leg_4 = new ModelRenderer(this, 50, 13);
      leg_4.addBox(-4F, 0F, 0F, 2, 10, 2);
      leg_4.setRotationPoint(-3F, 14F, -7F);
      leg_4.setTextureSize(64, 32);
      leg_4.mirror = true;
      setRotation(leg_4, 0F, 0F, 0F);
      Chair_top = new ModelRenderer(this, 0, 26);
      Chair_top.addBox(0F, 0F, -1F, 16, 1, 16);
      Chair_top.setRotationPoint(-8F, 13F, -7F);
      Chair_top.setTextureSize(64, 32);
      Chair_top.mirror = true;
      setRotation(Chair_top, 0F, 0F, 0F);
      Chari_rod_1 = new ModelRenderer(this, 15, 45);
      Chari_rod_1.addBox(0F, 0F, 0F, 2, 12, 1);
      Chari_rod_1.setRotationPoint(5F, 1F, 6F);
      Chari_rod_1.setTextureSize(64, 32);
      Chari_rod_1.mirror = true;
      setRotation(Chari_rod_1, 0F, 0F, 0F);
      Chari_rod_2 = new ModelRenderer(this, 8, 45);
      Chari_rod_2.addBox(0F, 0F, 0F, 2, 12, 1);
      Chari_rod_2.setRotationPoint(-7F, 1F, 6F);
      Chari_rod_2.setTextureSize(64, 32);
      Chari_rod_2.mirror = true;
      setRotation(Chari_rod_2, 0F, 0F, 0F);
      Chari_rod_3 = new ModelRenderer(this, 1, 45);
      Chari_rod_3.addBox(0F, 0F, 0F, 2, 12, 1);
      Chari_rod_3.setRotationPoint(-1F, 1F, 6F);
      Chari_rod_3.setTextureSize(64, 32);
      Chari_rod_3.mirror = true;
      setRotation(Chari_rod_3, 0F, 0F, 0F);
      Chair_rod_4 = new ModelRenderer(this, 1, 60);
      Chair_rod_4.addBox(0F, 0F, 0F, 16, 2, 1);
      Chair_rod_4.setRotationPoint(-8F, -1F, 6F);
      Chair_rod_4.setTextureSize(64, 32);
      Chair_rod_4.mirror = true;
      setRotation(Chair_rod_4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    leg_1.render(f5);
    leg_2.render(f5);
    leg_3.render(f5);
    leg_4.render(f5);
    Chair_top.render(f5);
    Chari_rod_1.render(f5);
    Chari_rod_2.render(f5);
    Chari_rod_3.render(f5);
    Chair_rod_4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void renderModel(float f) {
	  leg_1.render(f);
	    leg_2.render(f);
	    leg_3.render(f);
	    leg_4.render(f);
	    Chair_top.render(f);
	    Chari_rod_1.render(f);
	    Chari_rod_2.render(f);
	    Chari_rod_3.render(f);
	    Chair_rod_4.render(f);
	  
	  
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
